# Generated by Django 3.1.5 on 2021-02-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailapp", "0005_auto_20210202_0248_squashed_0006_auto_20210203_0152"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="alt",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
