# Generated by Django 3.1.5 on 2021-01-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"ordering": ["created"], "verbose_name_plural": "Businesses"},
        ),
        migrations.AddField(
            model_name="businesscategory",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
