# Generated by Django 3.1.5 on 2021-01-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business", options={"verbose_name_plural": "Businesses"},
        ),
        migrations.AlterField(
            model_name="business",
            name="price_point",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "$"), (2, "$$"), (3, "$$$"), (4, "$$$$")],
                null=True,
            ),
        ),
    ]
