# Generated by Django 3.1.5 on 2021-01-24 01:40

from django.db import migrations, models
import wawo.util.util


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="hero_image",
            field=models.ImageField(
                null=True, upload_to=wawo.util.util.file_url("businesses")
            ),
        ),
        migrations.AddField(
            model_name="businessimage",
            name="alt",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
