# Generated by Django 3.1.5 on 2021-01-28 01:10

from django.db import migrations, models
import wawo.util.util


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_businesscategory_color_hex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessevent",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=wawo.util.util.file_url("events")
            ),
        ),
    ]
