# Generated by Django 3.1.5 on 2021-01-28 01:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import wawo.util.util


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_auto_20210128_0110"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=wawo.util.util.file_url("businesses")),
                ),
                ("alt", models.CharField(max_length=100)),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Order of the image, smaller being displayed first",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_images",
                        to="directory.business",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
