# Generated by Django 3.1.5 on 2021-02-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0006_business_store_hours"),
    ]

    operations = [
        migrations.RemoveField(model_name="business", name="hero_image",),
    ]
