# Generated by Django 3.1.5 on 2021-01-14 02:27

from django.db import migrations, models
import django.db.models.deletion
import wawo.account.models
import wawo.util.util


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="account.user",
                    ),
                ),
                ("about", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "founder_first_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "founder_last_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "founder_title",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("display_founder_information", models.BooleanField(default=True)),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("account.user",),
            managers=[("objects", wawo.account.models.UserManager()),],
        ),
        migrations.AddField(
            model_name="user", name="birthday", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_account.user_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=wawo.util.util.file_url("profiles")
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_agreed",
            field=models.BooleanField(default=False),
        ),
    ]
