# Generated by Django 3.1.5 on 2021-01-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
        ("account", "0002_auto_20210114_0227"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(blank=True, to="directory.Business"),
        ),
    ]
